name: Unit Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 24.0.2 (npm 11.3+)
        uses: actions/setup-node@v4
        with:
          node-version: '24.0.2'
          cache: 'npm'

      - name: Clean install
        run: |
          rm -rf node_modules package-lock.json
          npm ci

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test
